name: snapcraft-snap

on: 
  push: 
    tags:
      - "3.9.[0-9]+**"
      - "v3.9.[0-9]+**"

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Configure
        run: "echo 'Action enabled: ${{ GITHUB_ACTION_ENABLED }}'"
        env:
          action_enabled: ${{ GITHUB_ACTION_ENABLED }}
          publish_on_github: ${{ PUBLISH_GITHUB }}
          publish_on_snapcraft: ${{ PUBLISH_SNAPCRAFT_STORE }}
        

      - uses: actions/checkout@v2
        if: ${{ GITHUB_ACTION_ENABLED }}

      - uses: frabert/replace-string-action@v1.1
        id: git-tag
        with:
          pattern: 'refs/tags/'
          string: ${{ github.ref }}
          replace-with: ''

      - uses: jhenstridge/snapcraft-build-action@v1
        id: snapcraft
        if: ${{ GITHUB_ACTION_ENABLED }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        if: ${{ PUBLISH_GITHUB && GITHUB_ACTION_ENABLED }}


      - name: Upload Release Asset to github
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./${{ steps.snapcraft.outputs.snap }}
          asset_name: ${{ github.workflow }}-${{ steps.git-tag.outputs.replaced }}
          asset_content_type: application/zip
        if: ${{ PUBLISH_GITHUB && GITHUB_ACTION_ENABLED }}


      - name: Upload release asset to snapcraft.io
        uses: jhenstridge/snapcraft-publish-action@master
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge
        if: ${{ PUBLISH_SNAPCRAFT_STORE && GITHUB_ACTION_ENABLED }}
